---
- name: Install local pgdg rpm
  yum: name=/usr/local/src/{{ rpm[rpm['ver']] }}

# PRM seems to create /var/log/pgsql file.
- name: Create PostgreSQL directory
  file: path={{ item }} state=directory recurse=yes mode=755 owner=postgres group=postgres
  with_items:
    - "{{ pgsql_log_dir }}"
    - "{{ pgarc }}"
  when: "'pgsql' in group_names"

- name: Create PGDATA
  file: path={{ pghome }} state=directory recurse=yes mode=700 owner=postgres group=postgres
  when: "'pgsql' in group_names"

- name: Install PostgreSQL
  # shell: ls -1 /usr/local/src/postgresql{{ pg_ver }}-*.rpm | xargs yum -y localinstall
  yum: name={{ item }}
  with_items:
    - "postgresql{{ pg_ver }}"
    - "postgresql{{ pg_ver }}-server"
    - "postgresql{{ pg_ver }}-contrib"
    - "postgresql{{ pg_ver }}-devel"

- name: Copy .bash_profile
  template: src=dot.bash_profile dest=/var/lib/pgsql/.bash_profile mode=644 owner=postgres group=postgres

- name: Workaround for pg_monz
  file: path={{ item }}/bin state=directory mode=755
  with_items:
    - "{{ pghome }}"
    - "{{ pghome }}/bin"
